// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Tui57VTCNE-Mxevvy30gjoqH7C1hrMo',
    appId: '1:526797996310:android:76aa7f270e3319fba75037',
    messagingSenderId: '526797996310',
    projectId: 'sadqapakistan-c1829',
    storageBucket: 'sadqapakistan-c1829.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3p71SomrLRV8JcQ4kM7QIc8PeYDnLvI',
    appId: '1:526797996310:ios:31d32701704685c0a75037',
    messagingSenderId: '526797996310',
    projectId: 'sadqapakistan-c1829',
    storageBucket: 'sadqapakistan-c1829.appspot.com',
    androidClientId: '526797996310-4u2a55tau0p74la87oqtenr9o0cje9pj.apps.googleusercontent.com',
    iosClientId: '526797996310-ngljh5r71u4mtqf7hl3ftrmkm944toen.apps.googleusercontent.com',
    iosBundleId: 'com.sadqa.pak.sadqapak',
  );
}
